[package]
name = "chekhov"
description = "very simple actor/message concurrency"
license = "GPLv3.0+ WITH Classpath-exception-2.0"
version = "0.1.0"
authors = ["Lee <lee@libertad.ucsd.edu>"]
readme = "REAMDE.md"
